<a href="https://colab.research.google.com/github/Vignesh424/Random_Forest_Iris_Demo_Implementation/blob/main/Random_forest_Iris_Demonstration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [440]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [441]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [442]:
columns = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [443]:
dataset = pd.read_csv(path, names = columns)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [444]:
# Data Preprocessing will be done using

X = dataset.iloc[:,:4].values
y = dataset.iloc[:,4].values

In [445]:
# Next, we will divide the data into train and test split. 
# The following code will split the dataset into 70% training data and 30% of testing data −

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [446]:
X_train.shape

(105, 4)

In [447]:
y_train.shape

(105,)

In [448]:
X_test.shape

(45, 4)

In [449]:
y_test.shape

(45,)

In [450]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(n_estimators=50)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [451]:
y_pred = classifier.predict(X_test)

In [452]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)



Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]


In [453]:
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)



Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.93      1.00      0.96        13
 Iris-virginica       1.00      0.92      0.96        13

       accuracy                           0.98        45
      macro avg       0.98      0.97      0.97        45
   weighted avg       0.98      0.98      0.98        45



In [454]:
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Accuracy: 0.9777777777777777
